export default [
    {
      path:'/',
      name:'LayOut',
      component:()=>import('@/views/LayOut.vue'),
      redirect:"/index",
      children:[
        {
          path:"/index",
          name:"index",
          component:()=>import("@/views/index/HomeIndex"),
        },
        {
          path:"orders/list",
          name:"orders_list",
          component:()=>import("@/views/order/OrdersList"),
          meta:{
            bread:["订单管理","订单列表"]
          },
          },
          {
            path:"waybill/in",
            name:"way_bill",
            component:()=>import("@/views/waybill/WayBill"),
            meta:{
              bread:["运单管理","运单列表"]
            }
        }

      ]
    },
    {
      path:'/login',
      name:'Login',
      component:()=>import('@/views/LoginVue.vue'),
    },
    {
      path:"*",
      name:"NotFound",
      component:()=>import("@/views/NotFound")
    }
  ]