export default [
    {
      path:"/",
      name:"LayOut",
      redirect:"/index",
      component:()=>import("@/views/LayOut"),
      children:[
        {
          path:"/index",
          name:"HomeIndex",
          component:()=>import("@/views/index/HomeIndex")
        },
        {
          path:"orders/list",
          name:"Order",
          component:()=>import("@/views/order/OrderList"),
          meta:{bread:["订单管理","订单列表"]}
        },
        {
          path:"waybill/list",
          name:"WayBill",
          component:()=>import("@/views/waybill/WayBillList"),
          meta:{bread:["运单管理","运单列表"]}
        },
        {
          path:"personal",
          component:()=>import("@/views/personal/PersonCenter"),
          meta:{bread:["个人中心"]}
        }
      ]
    },
    {
      path:"*",
      name:"NotFound",
      component:()=>import("@/views/NotFound")
    },
    {
      path:"/login",
      name:"Login",
      component:()=>import("@/views/LoginIn")
    }
  ]